[profile.default]
evm_version = "cancun"
src = "src"
out = "out"
libs = ["lib"]


[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
tenderly = "${TENDERLY_VIRTUAL_TESTNET_RPC}"
tenderly_optimism = "${TENDERLY_VIRTUAL_TESTNET_RPC_OPTIMISM}"


